### PR TITLE
Update metrics dependency to 0.22.3, lambda_runtime & lambda_http to 0.11

### PR DESCRIPTION
**Pull request by peterall**
Hi Brian, please consider this PR which bumps metrics, lambda_runtime and lambda_http dependencies. 

Since metrics 0.22 has a breaking public change I figured I'd also bump this crate version to 0.5.0.

Big thanks for this project! 👍

### CODE REVIEW

**Comment by andy128k** [comment]
`lambda_runtime` 0.11 was already released so this PR needs to be updated too.

**Comment by peterall** [comment]
Yeah, 0.11 also introduces tower-layering in the runtime so that should probably be used instead of a wrapper

**Comment by peterall** [comment]
Updated for `lambda_runtime` 0.11, would love your feedback @andy128k and @bmorin 😄

**Comment by andy128k** [comment]
@peterall Perfect! Deploying it already to prod. :smirk:

**Comment by bmorin** [comment]
Just saw this, need to deal with my day job but will review tonight.

ty so much.

**Comment by peterall** [comment]
No worries, thanks again for all your work on the project! 🙏

**Pull request merged**
